project:
  type: website
  output-dir: docs
  execute-dir: project
  render:
    - "*.qmd"
    - "**/*.qmd"
    - "!advice"

website:
  title: "STA 9750"
  description:
    Basic Software Tools for Data Analysis
  site-url: "https://michael-weylandt.com/STA9750/"
  repo-url: https://github.com/michaelweylandt/STA9750
  repo-actions: [edit, source, issue]
  favicon: _houndfavicon.png
  navbar:
    background: primary
    search: false
    right:
      - text: "Syllabus"
        href: "./syllabus.html"
      - text: "Pre-Assignments"
        href: "./preassignments.html"
      - text: "Labs"
        href: "./labs.html"
      - text: "Mini Projects"
        href: "./miniprojects.html"
      - text: "Course Project"
        href: "./project.html"
      - text: "Additional Resources and Course Policies"
        href: "./resources.html"
      - text: "Learning Objectives"
        href: "./objectives.html"
      - text: "Prior Offerings"
        menu:
        - text: "Spring 2025"
          href: "./archive/AY-2024-SPRING/"
        - text: "Fall 2024"
          href: "./archive/AY-2024-FALL/"
format:
  html:
    theme: sandstone
    margin-left: 0em
    toc: true
    code-copy: true
    code-link: true
    toc_depth: 5
  live-html:
    theme: sandstone
    margin-left: 0em
    toc: true
    code-copy: true
    code-link: true
    toc_depth: 5

execute:
  freeze: false

editor:
  mode: source
