#!/usr/bin/env Rscript
library(tidyverse)
library(glue)

## Auto-generate key dates file
system("soffice --convert-to csv key_dates.ods")

## Generate Google Calendar Formatted CSV for Student Events
DATES <- read_csv("key_dates.csv")

### i) First get lectures
LECTURES <- DATES |>
        filter(`Course Element` == "Class Session") |>
        mutate(Subject=paste("STA 9750 Lecture", `Item Number`),
               `Start Date`=Date,
               `Start Time`="6:05 PM",
               `End Date`=Date,
               `End Time`="9:00 PM",
               `All Day Event`="False",
               `Location`="Zoom [Link distributed via CUNY Brightspace]") |>
        select(-`Course Element`,
               -`Item Number`,
               -`Responsible Party`,
               -`Date`,
               -`Time`,
               -`Details`)

    `%rep_na%` <- function(x, y) ifelse(is.na(x), y, x)

ASSIGNMENTS <- DATES |>
        filter(`Responsible Party` == "Student") |>
        mutate(Subject = paste0("STA 9750 ",
                                str_replace(`Course Element`, "s$", ""),
                                " ",
                                `Item Number` %rep_na% "",
                                ": ",
                                Details),
               Subject = str_replace(Subject, " :", ":"),
               dt = paste(Date, Time),
               end = parse_date_time(dt, "%Y-%m-%d %H:%M%p"),
               start = end - minutes(30),
               `Start Date`=as_date(start),
               `End Date`=as_date(end),
               `Start Time`=format(start, "%I:%M %p"),
               `End Time`=format(end, "%I:%M %p"),
               `All Day Event`="False",
               `Location`=case_when(
                   `Course Element` == "Mini-Projects" ~ "Submitted via GitHub and Brightspace",
                   `Course Element` == "Pre-Assignments" ~ "Submitted via Brightspace",
                   str_detect(Details, "Team Roster Submission") ~ "Direct Submission to Instructor",
                   str_detect(Details, "Presentation") ~ "In-Class Presentation",
                   str_detect(Details, "Teammate Peer Evaluations") ~ "Submitted via Brightspace",
                   str_detect(Details, "Report") ~ "Submitted via GitHub and Brightspace"
               )) |>
        select(-`Course Element`,
               -`Item Number`,
               -`Responsible Party`,
               -`Date`,
               -`Time`,
               -`Details`,
               -dt,
               -start,
               -end
        )

bind_rows(LECTURES, ASSIGNMENTS) |>
        arrange(`Start Date`) |>
        write_csv(glue("key_dates_students_gcal.csv"))

## Build site

if(!require("quarto")){
    install.packages("quarto")
}
library(quarto)
if(!quarto::quarto_binary_sitrep()){
    stop("Something is wrong with your quarto installation.")
}

QMD_FILES <- list.files(recursive=TRUE,
                        pattern="*qmd",
                        full.names=TRUE)

QMD_FILES <- QMD_FILES |>
    str_subset("(archive|_)", negate=TRUE) |>
    str_subset("(advice|_)", negate=TRUE) |>
    str_subset("^_", negate=TRUE)

for(fname in QMD_FILES){
    cat("Rendering", fname, "\n")
    tryCatch(quarto::quarto_render(fname), error=function(e){})
}

# Process navbar in archive folders
cat("Adapting Archive Navbars\n")
ARCHIVE_HTML_FILES <- list.files("docs/archive/",
                                 recursive = TRUE,
                                 pattern=".*html$",
                                 full.names=TRUE)

library(rvest)
for(fname in ARCHIVE_HTML_FILES){
    if(!str_ends(fname, "html")) next
    html_old <- readLines(fname)

    html_links_old <- rvest::read_html(fname) |>
        html_element(".navbar") |>
        html_elements("a") |>
        html_attr("href")

    html_new <- html_old

    html_links_new <- html_links_old |>
        str_replace_all(fixed("../.././archive/"), "../") |>
        str_replace_all(fixed("../../"),"./") |>
        str_replace_all(fixed("././"), "./")

    archive_links_ix <- str_detect(html_links_old, "archive")
    html_links_new[archive_links_ix] <- html_links_old[archive_links_ix]

    # Vectorization works weirdly here, so do this in a loop
    for(link_ix in seq_along(html_links_old)){
        html_new <- str_replace_all(html_new,
                                    fixed(html_links_old[link_ix]),
                                    fixed(html_links_new[link_ix]))
    }


    writeLines(html_new, fname)
}

cat("Adding archive announcement bars\n")

for(fname in ARCHIVE_HTML_FILES){
    if(str_detect(fname, "slides")){
        cat("Skipping", fname, "as it is a set of slides\n")
        next
    }

    html_old <- readLines(fname)

    if(any(str_detect(html_old, "quarto-announcement"))){
        cat("Skipping", fname, "as it already has an announcement bar\n")
        next
    }

    cat("Adding archive bar to", fname, "\n")

    html_split <- str_split_fixed(paste(html_old, collapse="\n"), "</header>", 2)

    current_link <- str_replace(fname, "docs/archive/+AY-\\d{4}-(SPRING|FALL)/?", "../../")
    current_link <- str_replace(current_link, "\\.\\./\\.\\./(.*)/(.*)", "../../../\\1/\\2")

    add_in <- glue('
<div id="quarto-announcement" data-announcement-id="6a42bbecdcf2d6ce6b61d47c55fab2f9" class="alert alert-danger">
  <i class="bi bi-info-circle quarto-announcement-icon"></i>
  <div class="quarto-announcement-content">
    <strong>Warning</strong> - This page is for a prior offering of STA 9750. For the latest offering, click <a id="exit-archive-link" href="{current_link}">here</a>.
  </div>
</div>
</header>
')

    html_new <- c(html_split[[1]], add_in, html_split[[2]])
    writeLines(html_new, fname)
}

knitr::purl("tips.qmd",
            documentation=0L,
            output="docs/load_helpers.R")

system("git add docs/*")


if(!any(grepl("rstudio", search()))){q("no")}
