---
title: "{{< var course.short >}} - Software Tools for Data Analysis"
---

Welcome to the course website for {{< var course.short >}} 
({{< var course.semester >}})!

{{< var course.short >}} is an _Introduction to R_ targeted at students in the 
[MS in Business Analytics](https://zicklin.baruch.cuny.edu/academic-programs/graduate/ms/masters-in-business-analytics/), 
[MS in Statistics](https://zicklin.baruch.cuny.edu/academic-programs/graduate/ms/statistics/), 
and [MS in Quantitative Methods](https://zicklin.baruch.cuny.edu/academic-programs/graduate/ms/quantitative-methods-modeling/) 
programs. 

This site hosts the [Course Syllabus](./syllabus.html), 
[Course Policies](./resources.html), and [Course Learning 
Objectives](./objectives.html). Copies of these documents may also be
found on your [CUNY Brightspace](https://brightspace.cuny.edu).

Required course [pre-assignments](./preassignments.qmd), [labs](./labs.html), and 
[mini-projects](./miniprojects.html) can also be found on this site, as can
my lecture slides and information relevant to the [course project](./project.html).
Some helpful technical advice and tools can be found [here](./tips.html)

This offering of {{< var course.short >}} will be taught in a mixture of the
*flipped-classroom* and  *experiential-learning* formats. Roughly, this means
that most weeks, students will be asked to complete a small [_pre-assignment_](./preassignments.html) 
each week to introduce the core concept(s) covered in that week's lecture.
Each class period will be split between a brief lecture covering concepts in more
detail and an extended [_lab activity_](./labs.html) designed to build
familiarity and fluency with that week's subject matter. 

::: {#calendar}


There are quite a few moving parts to this course, so this [key dates file](./key_dates.csv)
or the list of upcoming course activities below may be useful:

```{r}
#| echo: false
#| message: false
#| warning: false
library(yaml)
library(glue)
library(tidyverse)
variables <- read_yaml("https://raw.githubusercontent.com/michaelweylandt/STA9750/refs/heads/main/_variables.yml")
course_repo  <- variables$course$repo
course_short <- variables$course$short

read_csv("key_dates.csv") |> 
    select(-`Significant Student Time`) |>
    mutate(Time2 = Time |> str_replace("11:", "23:") |> str_replace("6:", "18:")) |>
    arrange(Date, Time2) |> 
    select(-Time2) |>
    DT::datatable(options=list(searching=FALSE,
                               paging=TRUE),
                  caption=glue("Upcoming Important Dates for {course_short}"), 
                  elementId="calendar_table",
                  rownames=FALSE)
```


A CSV file suitable for import into Google Calendar with all assignment 
deadlines can be found [here](./key_dates_students_gcal.csv).

Instructions for how to do so can be found
[here](https://support.google.com/calendar/answer/37118?hl=en&co=GENIE.Platform=Desktop).
If you use another calendar system that cannot accept CSV files in this format, 
let me know and I will try to provide additional file formats. 

:::

<script>
// Update Calendar DataTables (created above in R) to show future events only
// 
// We set a one-time hook on each table (selected by ID) at its initial 'draw'
// event. This function checks the current date and compares it to the value
// in the fourth (date) column, deleting rows with past dates. After deletion,
// the table is re-drawn. 
//
// We use a one time hook (\$.one) as opposed to an everytime hook (\$.on) to 
// avoid an infinite loop. Since the table is not destroyed, just hidden, when
// moving from one tab to the other, this seems to be safe. 
$('#calendar_table').each(function(){
  $(this).one( 'draw.dt', function(){
    var filter_date = new Date();
    filter_date.setDate(filter_date.getDate() - 1);
    var filter_string = filter_date.toISOString().split('T')[0];
    $("table").DataTable().rows((idx, data) => data[3] < filter_string).remove().draw();
  });
});

</script>

Instructor: [Michael Weylandt](https://michael-weylandt.com)

