---
title: "{{< var course.short >}} - In-Class Labs"
---

Most weeks, the Thursday 'lecture' for {{< var course.short >}} will be dedicated to an in-class "lab". These ungraded labs are an opportunity to see how the concepts introduced in that week's [pre-assignment](./preassigns.html) are used in practice.

Labs:

- [Lab #01](./labs/lab01.html): `R`ev your Engines! Setting-Up `R` and `RStudio`
- [Lab #02](./labs/lab02.html): Getting Down with Markdown
- [Lab #03](./labs/lab03.html): `R`, These are your first steps...
- [Lab #04](./labs/lab04.html): Single Table Verbs, Group-Aware Filtering
- [Lab #05](./labs/lab05.html): Let us `Join` our Tables Together
- [Lab #07](./labs/lab07.html): More Thoughts on Plots
- [Lab #08](./labs/lab08.html): Advanced Plotting - Chloropleths and Cartograms
- [Lab #09](./labs/lab09.html): Data Import in `R`
- [Lab #11](./labs/lab11.html): Manipulating and Reading HTML in `R`
- [Lab #12](./labs/lab12.html): Strings and Stringy-Things
- [Lab #13](./labs/lab13.html): Inference and Prediction in `R`
