---
title: "STA/OPR 9750 - Mini Projects"
---

In lieu of traditional homework, STA/OPR 9750 has a series of **mini-projects**
designed to achieve several interlocking goals: 

1. Improve your skills at data analysis
2. Improve your improve your ability to give feedback on data analysis work
3. Seed a 'portfolio' of data science work you can demonstrate to potential employers

Each Mini-Project will be submitted via `GitHub`, an industry-standard code management
platform, as both raw analysis code and as a HTML document hosted on GitHub pages.

After each Mini-Project is submitted, 2-3 peer reviewers will be assigned to give
feedback and to assign an initial grade following an instructor provided rubric.
This feedback will be given *via* GitHub Issues. 

In order to ensure good peer feedback, the peer feedback will be evaluated by 
the instructor in a "meta-review" worth a small fraction of the overall grade. 

If you believe your mini-project has received inaccurate peer feedback, please
contact the instructor directly within **48 hours** of the peer feedback deadline.
No student-initiated requests for re-grading will be accepted after that time, though
the instructor may re-grade the work during the meta-review stage.


### Mini-Projects

#### Mini-Project #00: Course Set-Up

**Due Date:**

  - Released to Students: 2024-08-29
  - **Initial Submission: 2024-09-11 at 11:45pm**
  - **Peer Feedback: 2024-09-18 at 11:45pm**

In the ungraded [Mini-Project #00](./miniprojects/mini00.html), there is no data
analysis required, but you will set up the basic web tooling used to submit projects
#01 to #04. 

Note that, even though ungraded, Mini-Project #00 must be completed to remain
enrolled in this course and before any other Mini-Projects can be submitted. 

#### Mini-Project #01: TBA

**Due Dates:**

  - Released to Students: 2024-09-12
  - **Initial Submission: 2024-09-25 at 11:45pm**
  - **Peer Feedback: 2024-10-02 at 11:45pm**

#### Mini-Project #02: TBA

**Due Dates:**

  - Released to Students: 2024-09-26
  - **Initial Submission: 2024-10-23 at 11:45pm**
  - **Peer Feedback: 2024-10-30 at 11:45pm**

#### Mini-Project #03: TBA

**Due Dates:**

  - Released to Students: 2024-10-24
  - **Initial Submission: 2024-11-13 at 11:45pm**
  - **Peer Feedback: 2024-11-20 at 11:45pm**

#### Mini-Project #04: TBA

**Due Dates:**

  - Released to Students: 2024-11-14
  - **Initial Submission: 2024-12-04 at 11:45pm**
  - **Peer Feedback: 2024-12-11 at 11:45pm**
