---
title: "STA/OPR 9750 - Pre-Assignments"
---

In lieu of traditional homework, STA/OPR 9750 has weekly **pre-assignments**
designed to achieve several interlocking goals: 

1. Provide initial exposure to that week's topic before the lecture and lab session
2. Allow students with less previous programming experience more time to familiarize themselves with that week's topic
3. Allow students to submit questions to be covered in class

Each Pre-Assignment will be submitted via [CUNY Brightspace](https://brightspace.cuny.edu/)
and due the night before class (Wednesdays at 11:45). These are short assignments, 
typically only a few questions, so extensions will not be given outside of exceptional
circumstances. 

### Pre-Assignments

#### Pre-Assignment for Week #01

None.

#### Pre-Assignment for Week #02

**Due Date:**

  - Released to Students: 2024-08-29
  - **Due on Brightspace: 2024-09-04 at 11:45pm**

In [this Pre-Assignment](./preassigns/pa02.html), you will familiarize yourself
with the basics of `Markdown`, an easy way to write and format documents. In class,
we will use `Markdown` based tools to create dynamic data analysis documents
seamlessly combining code, text, and graphics. 

#### Pre-Assignment for Week #03

**Due Date:**

  - Released to Students: 2024-09-05
  - **Due on Brightspace: 2024-09-11 at 11:45pm**

TBA

#### Pre-Assignment for Week #04

**Due Date:**

  - Released to Students: 2024-09-12
  - **Due on Brightspace: 2024-09-18 at 11:45pm**

TBA

#### Pre-Assignment for Week #05

**Due Date:**

  - Released to Students: 2024-09-19
  - **Due on Brightspace: 2024-09-25 at 11:45pm**

TBA

#### Pre-Assignment for Week #06

None. 

The 2024-10-10 class session will be dedicated to [Course Project Proposals](./project.html).

#### Pre-Assignment for Week #07

**Due Date:**

  - Released to Students: 2024-10-10
  - **Due on Brightspace: 2024-10-16 at 11:45pm**

TBA

#### Pre-Assignment for Week #08

**Due Date:**

  - Released to Students: 2024-10-17
  - **Due on Brightspace: 2024-10-23 at 11:45pm**

TBA

#### Pre-Assignment for Week #09

**Due Date:**

  - Released to Students: 2024-10-24
  - **Due on Brightspace: 2024-10-30 at 11:45pm**

TBA

#### Pre-Assignment for Week #10

None. 

The 2024-11-07 class session will be dedicated to [Course Project Mid-Semester Check-Ins](./project.html).


#### Pre-Assignment for Week #11

**Due Date:**

  - Released to Students: 2024-11-07
  - **Due on Brightspace: 2024-11-13 at 11:45pm**

TBA

#### Pre-Assignment for Week #12

**Due Date:**

  - Released to Students: 2024-11-14
  - **Due on Brightspace: 2024-11-20 at 11:45pm**

TBA

#### Pre-Assignment for Week #13

**Due Date:**

  - Released to Students: 2024-11-28
  - **Due on Brightspace: 2024-12-04 at 11:45pm**

TBA

#### Pre-Assignment for Week #14

None. 

The 2024-12-12 class session will be dedicated to [Course Project Final Presentations](./project.html).
