---
title: "{{< var course.short >}} - Course Policies & Additional Resources"
---

## Course Resources

[R for Data Science](https://r4ds.hadley.nz/) (R4DS) is an excellent free
textbook covering much of the material of this course.

The [`tidyverse`](http://tidyverse.org) packages used throughout this course
have excellent documentation:

- [`readr`](https://readr.tidyverse.org)
- [`dplyr`](https://dplyr.tidyverse.org)
- [`tidyr`](https://tidyr.tidyverse.org)
- [`ggplot2`](https://ggplot2.tidyverse.org/)
- [`rvest`](https://rvest.tidyverse.org)


The [`quarto` guide](https://quarto.org/docs/guide/) is particularly useful.

Students may also benefit from the [Unofficial Solutions for R4DS](https://jrnold.github.io/r4ds-exercise-solutions/), 
the [Posit R Cheatsheets](https://posit.co/resources/cheatsheets/), 
[Statistical Infernece via Data Science](https://moderndive.com/), and the book
[Elegrant Graphics for Data Analysis](https://ggplot2-book.org/). 

The book [*Happy Git with R*](https://happygitwithr.com/) is particularly useful
for `git` usage. General `git` usage is also covered by the 
[Git Book](https://git-scm.com/book/en/v2).

The book [*Veridical Data Science*](https://vdsbook.com/) by Yu and Barter has lots
of useful advice on applied data analytics that may help with the course project. 

Students are encouraged to ask the instructor for additional resources as needed. 

### GitHub Resources

After you create your GitHub account in [Mini-Project 
 #00](./miniprojects/mini00.html), you should register for the [GitHub Student
Developer Pack](https://education.github.com/pack). This will give you increased
GitHub functionality as well as free access to [GitHub 
CoPilot](https://github.com/features/copilot), a coding assistance tool that
students in previous offerings of this course have found helpful.

The Student Developer Pack also gives you access to several helpful online
tutorials, including GitHub's official [Understanding
Markdown](https://education.github.com/experiences/understanding_markdown) and
[Intro to GitHub](https://education.github.com/experiences/intro_to_github)
courses. 


### Course Discussion Board

{{< var course.short >}} will use `Piazza` as the course discussion board.
Students are encouraged to direct all questions about course topics or logistics
to Piazza; use of a public anonymous discussion board allows students to benefit
from the insights of their classmates and allows instructors to answer questions
publicly to the benefit of all students. 

Students are encouraged to use Piazza's private question feature if they need to
contact the instructor directly. Please only use private questions for personal
inquiries: questions about the technical substance of the course can and should
be asked (pseudonymously) in the public section of Piazza. 

Piazza login information will be distributed through CUNY Brightspace.

### Communication Resources

Written and oral communication is an important element of this course. 

The [Baruch Writing Center](https://blogs.baruch.cuny.edu/writingcenter/) offers
free support to all Baruch students; students can meet with a professional writing
consultant one-to-one (in person, in NVC 8-185, or online, by video, audio, and
text-based chat) and in group workshops. Writing Center consultants will work
collaboratively with you to deepen your writing and English language skills.
At any step in the process, they’ll help you become a more independent, confident,
and versatile writer.[^0]

Baruch's [Tools for Clear Speech](https://tfcs.baruch.cuny.edu/) program improves
the pronunciation, fluency, and pragmatic abilities of English language learners
and non-native English speakers at Baruch College.  TfCS participants achieve more
effective and intelligible communication, developing skills that empower them
to succeed in their classrooms, careers, and beyond. TfCS offers a range of free
face-to-face and online services with our professional Speech Consultants,
including One-to-One Sessions, small-group Focused Skills Series sessions,
large-group Overview Workshops, interview and career preparation, and weekly
Conversation Hours.

### Computing Resources

All software used in this course is [Free and Open-Source Software](https://en.wikipedia.org/wiki/Free_and_open-source_software) that can be installed on your personal machine without cost. Students will need to install, at a minimum, 

- [`R`](https://cloud.r-project.org/)
- [`rstudio` Desktop Edition](https://posit.co/download/rstudio-desktop/)
- [`quarto`](https://quarto.org/docs/get-started/)

Thanks to the [Binder project](https://mybinder.org/), we are also able to provide free _virtual machines_ equipped with all course software pre-installed:

- [RStudio](https://mybinder.org/v2/gh/michaelweylandt/STA9750/main?urlpath=rstudio)
- [Command Line Access](https://mybinder.org/v2/gh/michaelweylandt/STA9750/main)

CUNY also provides a Windows-based RStudio virtual machine through [Apporto](https://cuny.apporto.com/).

Please note that these are _transient instances_ and any work saved on these 
machines may be lost without warning. 

### Helper Functions

Several "helper" functions may be found [here](./tips.html). These include 
functionality to verify that assignments and feedback have been properly
submitted on GitHub, to count words on a page, *etc.* Note that these are a new
addition to this course, so please contact the instructor if they do not appear
to be working properly.

## Course Policies

### Academic Integrity Policy

I fully support CUNY’s [Policy on Academic
Integrity](https://studentaffairs.baruch.cuny.edu/wp-content/uploads/sites/6/2024/08/CUNY-Academic-Integrity-Policy-2024.pdf),
which states, in part:

> Academic dishonesty is prohibited in The City University of New York. Penalties for 
  academic dishonesty include academic sanctions, such as failing or otherwise
  reduced grades, and/or disciplinary sanctions, including suspension or expulsion.

> Academic integrity is at the core of a college or university education. Faculty
  assign essays, exams, quizzes, projects, and so on both to extend the learning 
  done in the classroom and as a means of assessing that learning. When students 
  violate the academic integrity policy (i.e., "cheat"), they are committing an
  act of theft that can cause real harm to themselves and others including, but
  not limited to, their classmates, their faculty, and the caregivers who may be
  funding their education. Academic dishonesty confers an unfair advantage over
  others, which undermines educational equity and fairness. Students who cheat
  place their college’s accreditation and their own future prospects in jeopardy.

Academic sanctions in this class will range from an **F on the Assignment** to
an **F in this Course**. A report of suspected academic dishonesty will be sent
to the Office of the Dean of Students. 

Students are encouraged to contact the instructor with any questions or concerns
related to matters of academic integrity.


### External Resources Use Policy

For the coding elements of this course, students are encouraged to use freely
available online resources, including question-and-answer fora such as StackOverflow.
You may also use AI-driven developer tools such as GitHub Co-Pilot. Paid services
are not allowed. On each assignment, you will be asked to list external resources
used on each assignment. You are ultimately responsible for the correctness of any
submitted materials - "the AI told me so"" is not a valid defense.

*Note on ChatGPT and Related Large-Language Models*: You **may not** use 
large-language models to complete any assignment in this course. Specifically, 
you may not use tools where you describe the course assignment in natural language
and receive (pseudo-)code output. While these tools are powerful, and often
surprisingly accurate, for this task, using them in this manner will undermine
the [learning objectives](./objectives.html) of this course.

For the written elements of this course (_e.g._ Project Final Report), standard
academic expectations of attribution and citation are in place. This will be
covered in more detail in the course project documents. 

Students are _highly encouraged_ to collaborate on homework assignments, but
each student is required to individually and complete each assignment. If
substantially identical assignments are submitted, the instructor may require
each student to individually demonstrate their understanding of the material.
Collaborators should be listed at the end of each submitted assignment along with
a statement of contributions.


### Unexcused Abscence Policy

Attendance is not required, but lecture recordings will not be provided.
Students are responsible for the content of all sessions missed.


### Late Work Policy {#late-work-policy}

Late work will not be accepted except in extraordinary and unforeseeable
circumstances. Students submitting late work should provide supporting documentation
to the Office of the Dean of Students; ODS will provide the instructor with a letter
authorizing late work submission as appropriate. 

All assignment submission technology used in this course allows
multiple submissions, so students are encouraged to submit early and often
to avoid any technology troubles associated with late submission. 

Note that late work is allowed consistent with specific pre-arranged
course accommodations as noted below.

## Course Accommodations

### Disability Services

It is [CUNY policy](https://www.cuny.edu/about/administration/offices/legal-affairs/policies-resources/reasonable-accommodations-and-academic-adjustments/v-accommodations/)
to provide Accommodations and Academic Adjustments to students with disabilities. 

Any student who has a disability who may need accommodations in this class
should register as early as possible with [Student Disability
Services](https://studentaffairs.baruch.cuny.edu/student-disability-services/).
Your registration with Student Disability Services is confidential, and is not
recorded on your Baruch Academic Record. SDS can be reached by email at
[disability.services@baruch.cuny.edu](mailto:disability.services@baruch.cuny.edu),
by phone at [646-312-4590](tel:646-312-4590), or in person at NVC 2-272.

Please note that the instructor cannot provide accommodations unless requested by SDS.

### Religious Accomodations

It is [CUNY policy](https://www.cuny.edu/about/administration/offices/legal-affairs/policies-resources/reasonable-accommodations-and-academic-adjustments/vi-religious-accommodations/)
to provide accommodations for students' sincerely held religious beliefs. If a religious
accommodation is requested, please contact the instructor at least two weeks in advance.

## Additional Baruch and CUNY Benefits

As Baruch students, you have access to a variety of cultural and education
benefits including: 

- Free [New York Times subscription](https://guides.newman.baruch.cuny.edu/newyorktimes)
- Free [Wall Street Journal subscription](https://guides.newman.baruch.cuny.edu/wallstreetjournal)
- Free [Barron's Subscription](https://zicklin.baruch.cuny.edu/current/graduate-advisement-hub/campus-resources/free-subscriptions-for-zicklin-students/) (Zicklin only)
- Free and Discounted [Museum Admissions](https://www.cuny.edu/academics/current-initiatives/cuny-arts/)
- Discounted [Carnegie Hall performances](https://www.carnegiehall.org/Events/Discount-Programs/Student-Insider)
- [GitHub Student Developer Pack](https://education.github.com/pack)
- [Free and Discounted Amazon Prime](https://www.amazon.com/Amazon-Student/b?node=668781011)

among many others. 

More will posted as I discover them.

## Care Resources for Students[^1]

Take care of yourself. Do your best to maintain a healthy lifestyle this
semester by eating well, exercising, avoiding drugs and alcohol, getting
enough sleep and taking some time to relax. This will help you achieve your
goals and cope with stress. 

All of us benefit from support during times of struggle. You are not alone.
Asking for support sooner rather than later is often helpful. 

This course is intended to be **demanding**, but not **difficult**. If you feel
like you are struggling, please reach out sooner rather than later.
Swimming long-distances in choppy waters builds strength: drowning doesn't.

### Mental Health Resources

If you or anyone you know experiences significant academic stress, difficult
life events, or feelings like anxiety or depression, I strongly encourage you
to seek support.

The [Baruch Counselling Center](https://studentaffairs.baruch.cuny.edu/counseling/)
is here to help. You can visit them in person at 137 E 25th St, 9th floor
or call them at [646-312-2155](tel:646-312-2155) during normal business hours;
you can make an appointment online
[here](https://baruch.az1.qualtrics.com/jfe/form/SV_a4NCaYrV2Sk1cyg). For more
immediate support, please call NYC WELL ([1-888-NYC-WELL](tel:1-888-NYC-WELL) or [1-888-692-9355](tel:1-888-692-9355)). 

Asking for help is often difficult: consider reaching out to a friend,
family, or a member of the faculty you trust for help getting connected to
support that can help. 

If you are worried about a friend or classmate, consider reaching out to the
[Baruch Campus Intervention 
Team](https://studentaffairs.baruch.cuny.edu/campus-intervention-team/).

### Physical Health

[Healthy CUNY](https://www.healthycuny.org/) promotes well-being and a culture
of health in order to foster the academic and life success of all CUNY students.
They can connect you with a variety of [campus-](https://www.healthycuny.org/cuny-health-centers)
and [community](https://www.healthycuny.org/community-health-resources)-based
healthcare providers. 

[Baruch Health Services](https://studentaffairs.baruch.cuny.edu/health/)
provides students with a full range of clinical health services. Call
[646-312-2040](tel:646-312-2040) or email
[StudentHealthCareCenter@baruch.cuny.edu](mailto:StudentHealthCareCenter@baruch.cuny.edu)
to make an appointment.

### Food Security

All CUNY students have access to [CUNY Food
Pantries](https://www.cuny.edu/about/administration/offices/transformation/cuny-cares/food-pantry/)
located throughout the five boroughs, thanks to the [CUNY
CARES](https://www.cuny.edu/about/administration/offices/transformation/cuny-cares/)
program. CUNY CARES is also able to help qualifying students with [SNAP ("Food Stamps")
enrollment](https://www.cuny.edu/current-students/student-affairs/student-services/snap/).

On campus, you can also access the [Bearcat Food Pantry](https://studentaffairs.baruch.cuny.edu/dean-of-students/bearcat-food-pantry/).

#### Financial Security
Baruch students experiencing heightened financial stress have access to 
[Student Emergency Grants](https://studentaffairs.baruch.cuny.edu/dean-of-students/emergencyfunds/)
administered through the Office of the Dean of Students. 
Note that funds are also available for students experiencing immigration-related
financial stress.

### Immigration Status

[CUNY Citizenship Now!](https://www.cuny.edu/about/administration/offices/communications-marketing/citizenship-now/)
provides confidential, high-quality immigration law services to all CUNY students. 

Note that Citizenship Now!'s primary Manhattan office is located in the Heights,
not on the Baruch campus and that an appointment is strongly recommended. Call
[646-664-9350](tel:646-664-9350) during standard business hours for more
information or to make an appointment

[^0]: Descriptions of Baruch and CUNY resources adapted from program websites.

[^1]: Language adapted from Professor Ryan Tibshirani (UC Berkeley).
