---
title: "STA/OPR 9750 - Course Syllabus"
---

### Instructor

-   [Professor Michael Weylandt](https://michael-weylandt.com)
-   Department of Information Systems & Statistics
-   Zicklin School of Business
-   Baruch College, CUNY

### Course Meetings

#### Lecture / Lab Sessions

-   Virtual (Synchronous Online)
-   Thursdays 6:05pm-9:00pm
    -   Zoom link provided via Brightspace

#### Office Hours

-   In-Person:
    -   VV 11-246 TBD
-   Virtual:
    -   Thursdays 4:30pm-5:30pm
    -   Zoom link provided via Brightspace

### Grading

-   24% [Weekly Pre-Assignments](./preassignments.html)
    -   3% Each (best eight of ten: lowest two dropped)
    -   Submission *via* Brightspace
-   36% [Mini Projects](./miniprojects.html)
    -   7% Each (four total)
    -   2% per Peer Feedback (Meta-Review)
-   40% [Course Project](./project.html)
    -   5% Proposal
    -   5% Mid-term Check-In
    -   10% Final Presentation
    -   10% Final Report
    -   10% Individual Evaluation

*Opportunities for Extra Credit:* Several opportunities for extra credit will be made available. These include:

1.  Participation in Course Discussion Board (piazza)
2.  Correction of errors in published course materials (first Github pull request)
3.  Submission of homework from other STA courses completed using `R`. (Note that the assignment must not ordinarily require `R`: this is *extra* credit.)

Final course grades will be curved in accordance with relevant program, departmental, school, and college policies.

### Tentative Course Schedule

+--------+--------------------+-------------------------------------------+----------------------------------+------------------------------+---------------------------------------------------------------------------------------+---------------------------------------------------------------------------------+
| Week   | Lecture Date       | Topics                                    | Pre-Assignment                   | In-Class Lab                 | Mini Projects                                                                         | Additional Notes                                                                |
+:======:+===================:+:==========================================+:================================:+:============================:+=======================================================================================+================================================================================:+
| 1      | August 29, 2024    | 1.  Course Overview                       | None                             | [Lab #1](./labs/lab01.html)  | [Mini Project #0](./miniprojects/mini00.html) assigned. Due September 11st at 11:45pm |                                                                                 |
|        |                    | 2.  `R` and `RStudio`                     |                                  |                              |                                                                                       |                                                                                 |
|        |                    | 3.  `git` and GitHub                      |                                  |                              |                                                                                       |                                                                                 |
|        |                    | 4.  Basic Principles of "Clean Code"      |                                  |                              |                                                                                       |                                                                                 |
+--------+--------------------+-------------------------------------------+----------------------------------+------------------------------+---------------------------------------------------------------------------------------+---------------------------------------------------------------------------------+
| 2      | September 5, 2024  | 1.  Markdown & Quarto                     | [PA #02](./preassigns/pa02.html) | [Lab #2](./labs/lab02.html)  |                                                                                       |                                                                                 |
|        |                    | 2.  GitHub Pages                          |                                  |                              |                                                                                       |                                                                                 |
|        |                    | 3.  Getting Help                          |                                  |                              |                                                                                       |                                                                                 |
|        |                    | 4.  Course Project Overview               |                                  |                              |                                                                                       |                                                                                 |
+--------+--------------------+-------------------------------------------+----------------------------------+------------------------------+---------------------------------------------------------------------------------------+---------------------------------------------------------------------------------+
| 3      | September 12, 2024 | First Steps with `R`:                     | [PA #03](./preassigns/pa03.html) | [Lab #3](./labs/lab03.html)  | [Mini Project #1](./miniprojects/mini01.html) assigned. Due September 25th at 11:45pm | Peer Feedback on Mini Project #0 due September 18th at 11:45pm.                 |
|        |                    |                                           |                                  |                              |                                                                                       |                                                                                 |
|        |                    | 1.  Vectors                               |                                  |                              |                                                                                       |                                                                                 |
|        |                    | 2.  Subsetting                            |                                  |                              |                                                                                       |                                                                                 |
|        |                    | 3.  Control Flow                          |                                  |                              |                                                                                       |                                                                                 |
|        |                    | 4.  Function Calls                        |                                  |                              |                                                                                       |                                                                                 |
+--------+--------------------+-------------------------------------------+----------------------------------+------------------------------+---------------------------------------------------------------------------------------+---------------------------------------------------------------------------------+
| 4      | September 19, 2024 | Tidy Data Manipulation I:                 | [PA #04](./preassigns/pa04.html) | [Lab #4](./labs/lab04.html)  |                                                                                       |                                                                                 |
|        |                    |                                           |                                  |                              |                                                                                       |                                                                                 |
|        |                    | 1.  Single Table Operations               |                                  |                              |                                                                                       |                                                                                 |
|        |                    | 2.  Factors                               |                                  |                              |                                                                                       |                                                                                 |
|        |                    | 3.  Dates & Times                         |                                  |                              |                                                                                       |                                                                                 |
+--------+--------------------+-------------------------------------------+----------------------------------+------------------------------+---------------------------------------------------------------------------------------+---------------------------------------------------------------------------------+
| 5      | September 26, 2024 | 1.  Multi-Table Operations (Joins)        | [PA #05](./preassigns/pa05.html) | [Lab #5](./labs/lab05.html)  | [Mini Project #2](./miniprojects/mini02.html) assigned. Due October 23rd at 11:45pm   | Peer Feedback on Mini Project #1 due October 2nd at 11:45pm.                    |
|        |                    | 2.  Pivots                                |                                  |                              |                                                                                       |                                                                                 |
|        |                    | 3.  Working with Missing Data             |                                  |                              |                                                                                       | No class next week (October 3rd - Rosh Hashanah)                                |
+--------+--------------------+-------------------------------------------+----------------------------------+------------------------------+---------------------------------------------------------------------------------------+---------------------------------------------------------------------------------+
| 6      | October 10, 2024   | **Project Proposal Presentations**        |                                  |                              |                                                                                       | In-Class Project Proposals                                                      |
+--------+--------------------+-------------------------------------------+----------------------------------+------------------------------+---------------------------------------------------------------------------------------+---------------------------------------------------------------------------------+
| 7      | October 17, 2024   | Plotting I: Static Plots                  | [PA #07](./preassigns/pa07.html) | [Lab #7](./labs/lab07.html)  |                                                                                       | Peer Feedback on Project Proposal Presentations due October 16th at 11:45pm.    |
+--------+--------------------+-------------------------------------------+----------------------------------+------------------------------+---------------------------------------------------------------------------------------+---------------------------------------------------------------------------------+
| 8      | October 24, 2024   | Plotting II:                              | [PA #08](./preassigns/pa08.html) | [Lab #8](./labs/lab08.html)  | [Mini Project #3](./miniprojects/mini03.html) assigned. Due November 13th at 11:45pm  | Peer Feedback on Mini Project #2 due October 30th at 11:45pm.                   |
|        |                    |                                           |                                  |                              |                                                                                       |                                                                                 |
|        |                    | 1.  Advanced `ggplot2`                    |                                  |                              |                                                                                       |                                                                                 |
|        |                    | 2.  Interactive Plots                     |                                  |                              |                                                                                       |                                                                                 |
+--------+--------------------+-------------------------------------------+----------------------------------+------------------------------+---------------------------------------------------------------------------------------+---------------------------------------------------------------------------------+
| 9      | October 31, 2024   | Data Import                               | [PA #09](./preassigns/pa09.html) | [Lab #9](./labs/lab09.html)  |                                                                                       |                                                                                 |
+--------+--------------------+-------------------------------------------+----------------------------------+------------------------------+---------------------------------------------------------------------------------------+---------------------------------------------------------------------------------+
| 10     | November 7, 2024   | **Mid-Semester Project Presentation**     |                                  |                              |                                                                                       | Project Mid-Semester Check-In                                                   |
+--------+--------------------+-------------------------------------------+----------------------------------+------------------------------+---------------------------------------------------------------------------------------+---------------------------------------------------------------------------------+
| 11     | November 14, 2024  | Elements of Web Scraping                  | [PA #11](./preassigns/pa11.html) | [Lab #11](./labs/lab11.html) | [Mini Project #4](./miniprojects/mini04.html) assigned. Due December 4th at 11:45pm   |                                                                                 |
+--------+--------------------+-------------------------------------------+----------------------------------+------------------------------+---------------------------------------------------------------------------------------+---------------------------------------------------------------------------------+
| 12     | November 21, 2024  | 1.  Strings & Regular Expressions         | [PA #12](./preassigns/pa12.html) | [Lab #12](./labs/lab12.html) | Peer Feedback on Mini Project #3 due November 20th at 11:45pm.                        | Peer Feedback on Mid-Semester Project Presentation due November 27th at 11:45pm |
|        |                    | 2.  Classical Statistical Modeling in `R` |                                  |                              |                                                                                       |                                                                                 |
|        |                    |                                           |                                  |                              |                                                                                       | No class next week (November 28th - Thanksgiving)                               |
+--------+--------------------+-------------------------------------------+----------------------------------+------------------------------+---------------------------------------------------------------------------------------+---------------------------------------------------------------------------------+
| 13     | December 5, 2024   | Predictive Modeling in `R`                | [PA #13](./preassigns/pa13.html) | [Lab #13](./labs/lab13.html) |                                                                                       |                                                                                 |
+--------+--------------------+-------------------------------------------+----------------------------------+------------------------------+---------------------------------------------------------------------------------------+---------------------------------------------------------------------------------+
| 14     | December 12, 2024  | **Final Presentations**                   |                                  |                              | Peer Feedback on Mini Project #4 due December 11th at 11:45pm.                        |                                                                                 |
+--------+--------------------+-------------------------------------------+----------------------------------+------------------------------+---------------------------------------------------------------------------------------+---------------------------------------------------------------------------------+

: {.hover}

All syllabus provisions subject to change with suitable advance notice.
