```{r}
#| echo: false
#| message: false
#| warning: false
library(glue)
library(gt)
library(rlang)
library(yaml)
library(purrr)
library(jsonlite)
library(tidyverse)

REPO_NAME <- read_yaml("_variables.yml")$course$repo
get_mp_title <- function(N){
    mp_file <- glue("mini/mini0{N}.qmd")
    mp_text <- readLines(mp_file, n=50)
    
    header_end <- which(grepl("---", mp_text))[2]
    
    header_info <- yaml.load(readLines(mp_file, n=header_end))
    
    header_info$mp_title %||% "TBD"
}


get_mp_application <- function(N){
    mp_file <- glue("mini/mini0{N}.qmd")
    mp_text <- readLines(mp_file, n=50)
    
    header_end <- which(grepl("---", mp_text))[2]
    
    header_info <- yaml.load(readLines(mp_file, n=header_end))
    
    header_info$mp_application %||% "TBD"
}


get_mp_rhetoric <- function(N){
    mp_file <- glue("mini/mini0{N}.qmd")
    mp_text <- readLines(mp_file, n=50)
    
    header_end <- which(grepl("---", mp_text))[2]
    
    header_info <- yaml.load(readLines(mp_file, n=header_end))
    
    header_info$mp_rhetoric %||% "TBD"
}


get_mp_skills <- function(N){
    mp_file <- glue("mini/mini0{N}.qmd")
    mp_text <- readLines(mp_file, n=50)
    
    header_end <- which(grepl("---", mp_text))[2]
    
    header_info <- yaml.load(readLines(mp_file, n=header_end))
    
    header_info$mp_skills %||% "TBD"
}

get_mp_assigned <- function(N){
    read_csv("key_dates.csv", 
             show_col_types=FALSE) |> 
        filter(`Course Element` == "Mini-Projects", 
               `Item Number`== N, 
               str_detect(Details, "Released"), 
               !str_detect(Details, "Peer")) |>
        pull(Date)
}

get_mp_deadline <- function(N, as_date_obj = FALSE){
    row <- read_csv("key_dates.csv", 
                    show_col_types=FALSE) |> 
                filter(`Course Element` == "Mini-Projects", 
                       `Item Number`== N, 
                       str_detect(Details, "Due"), 
                      !str_detect(Details, "Peer"))
    
    if(as_date_obj) return(row |> pull(Date))
    
    row |>
        mutate(due = paste(Date, "at", Time)) |>
        pull(due)
}

get_mp_pf_assigned <- function(N){
    read_csv("key_dates.csv", 
             show_col_types=FALSE) |> 
        filter(`Course Element` == "Mini-Projects", 
               `Item Number`== N, 
               str_detect(Details, "Assigned"), 
               str_detect(Details, "Peer")) |>
        pull(Date)
}



get_mp_pf_deadline <- function(N){
    read_csv("key_dates.csv", 
             show_col_types=FALSE) |> 
        filter(`Course Element` == "Mini-Projects", 
               `Item Number`== N, 
               str_detect(Details, "Peer"), 
               str_detect(Details, "Due")) |>
        pull(Date)
}

get_pa_deadline <- function(N){
    read_csv("key_dates.csv", 
             show_col_types=FALSE) |> 
        filter(`Course Element` == "Pre-Assignments", 
               `Item Number`== N, 
               str_detect(Details, "Due"), 
               !str_detect(Details, "Peer")) |>
        mutate(due = paste(Date, "at", Time)) |>
        pull(due)
}

get_mp_submitted <- function(N){
    ISSUES <- read_json(glue("https://api.github.com/repos/michaelweylandt/{REPO_NAME}/issues?per_page=100&state=open"))
    
    KEEP_ISSUES <- ISSUES |> keep(\(x) x |> 
                                      pluck("labels") |> 
                                      map_chr("name") |>
                                      str_detect(glue("Mini-Project #0{N}")) |>
                                      any()
                                  )
    
    
    PASSED_CHECKS <- KEEP_ISSUES |> keep(\(x) x |> 
                                      pluck("labels") |> 
                                      map_chr("name") |>
                                      str_detect("Passed Automated Checks") |>
                                      any()
                                  )
    
    
    N_SUBMITTED <- length(KEEP_ISSUES)
    N_COMPLETED <- length(PASSED_CHECKS)
    N_NEED_WORK <- N_SUBMITTED - N_COMPLETED
    
    list(n_submitted = N_SUBMITTED, 
         n_completed = N_COMPLETED,
         n_need_work = N_NEED_WORK)
}

get_project_due_date <- function(element = c("individual_report", 
                                             "group_report", 
                                             "peer_evaluation", 
                                             "team_formation", 
                                             "proposal")){
    
    element <- match.arg(element)
    
    search_string = case_match(element, 
                               "team_formation" ~ "Team Roster",
                               "individual_report" ~ "Individual Report", 
                               "group_report" ~ "Summary Report",
                               "peer_evaluation" ~ "Peer Evaluation", 
                               "proposal" ~ "Project Proposal")
    
    read_csv("key_dates.csv", 
             show_col_types=FALSE) |> 
        filter(`Course Element` == "Course Project", 
               str_detect(Details, search_string)) |>
        pull(Date)
}

next_session <- session + 1

DATES   <- read_csv("key_dates.csv", show_col_types=FALSE)
TODAY   <- DATES |> filter(`Course Element` == "Class Session", 
                           `Item Number` == session)

TODAY_TOPIC <- TODAY |>
    slice_head(n=1) |>
    pull(Details) 

if(str_detect(TODAY_TOPIC, "Lecture")){
  lecture <- str_extract(TODAY_TOPIC, "^Lecture #(\\d{2}):", group=1) |> as.integer()
  next_lecture <- lecture + 1
} else {
  lecture <- NA
  next_lecture <- NA
}

ROSTER_FILE <- read_yaml("_teaching.yml") |>
    pluck("gradedir") |>
    file.path("roster.json")

TEAMS_FILE <- read_yaml("_teaching.yml") |> 
    pluck("gradedir") |> 
    file.path("teams.json")

PROJ_RELEASE <- DATES |> 
    filter(Details == "Course Project Description Released") |>
    pull(Date)

ROSTERS <- get_project_due_date("team_formation")
PROPOSALS <- get_project_due_date("proposal")

if(file.exists(ROSTER_FILE)){
    N_TEAMS <- ROSTER_FILE |> 
        read_json(simplify=TRUE) |> 
        pull(project_team) |> 
        max(na.rm=TRUE)
    
    N_ON_TEAM <- ROSTER_FILE |> 
        read_json(simplify=TRUE) |> 
        filter(!is.na(project_team)) |> 
        NROW()
    
    N_NO_TEAM <- ROSTER_FILE |> 
        read_json(simplify=TRUE) |> 
        filter(is.na(project_team)) |> 
        NROW()

} else {
    N_TEAMS <- N_ON_TEAM <- N_NO_TEAM <- NA
}

set.seed(9750+session)

INITIALS <- ROSTER_FILE |> 
    read_json(simplify=TRUE) |> 
    filter(active) |>
    mutate(name_split = str_split(name, " "), 
           initials = map_chr(name_split, \(x) paste(str_sub(x, end=1), collapse=""))) |>
    group_by(project_team) |>
    summarize(initials = reduce(initials, \(x, y) paste(x, y, sep="+"))) |>
    mutate(initials = str_remove_all(initials, "[^+[:alpha:]]"))

if(file.exists(TEAMS_FILE) & file.info(TEAMS_FILE)$size > 0){
    TEAMS <- TEAMS_FILE |> 
        read_json(simplify=TRUE) 
} else {
    TEAMS <- data.frame(number = seq(NROW(INITIALS)), name="TBD")
}

TEAMS <- inner_join(TEAMS, INITIALS, join_by(number == project_team)) |>
    slice_sample(prop=1)

BREAKOUT_TABLE <- TEAMS |> 
    mutate(breakout = row_number(), 
           display = if_else(name == "TBD", 
                             initials, 
                             glue("{name} ({initials})"))) |>
    select(breakout, display) |>
    gt(id="team_room_assignments") |>
    cols_label(breakout = if(is.na(lecture)) md("**Presentation Order**") else md("**Breakout Room**"), 
               display = md("**Team**")) |>
    cols_align(everything(), align="center") |>
    tab_options(table.width = pct(100), 
                table.font.size = pct(80))
```

## {{< var course.short >}} Week {{< meta session >}} 

Today: `r TODAY_TOPIC`

These slides can be found online at: 

```{r}
#| message: false
#| echo: false
library(yaml)
url_base <- read_yaml("_variables.yml")$course$`web-url`
url_file <- sprintf("slides/slides%02g.html", session)

url_full <- paste0(url_base, url_file)
```

> [`r url_full`](`r url_full`)

```{r}
#| echo: false
#| results: "asis"
if(!is.na(lecture)) cat("In-class activities can be found at: ")
```

```{r}
#| message: false
#| echo: false
#| results: "asis"
url_base <- read_yaml("_variables.yml")$course$`web-url`
url_file <- sprintf("labs/lab%02g.html", lecture)

url_full <- paste0(url_base, url_file)

if(!is.na(lecture)) I(glue("> <{url_full}>"))
```

## Upcoming TODO

Upcoming student responsibilities:

```{r}
#| message: false
#| echo: false
library(gt)
read_csv("key_dates.csv", 
         show_col_types=FALSE) |>
    filter((`Responsible Party` == "Student") | (is.na(`Responsible Party`))) |>
    mutate(Time2 = Time |> str_replace("11:", "23:") |> str_replace("6:", "18:")) |>
    filter((Date > class_date) | 
           ((Date == class_date) & str_detect(Time2, "23"))) |>
    mutate(Details = case_when(
            is.na(`Item Number`) ~ Details, 
            TRUE ~ str_replace(Details, "Due", sprintf("#%02g Due", `Item Number`))
           )
    ) |>
    arrange(Date, Time2) |> 
    select(Date, Time, Details) |> 
    filter(Date <= class_date + 28) |>
    gt(id=glue("schedule_table_session_{session}")) |>
    tab_options(table.width = pct(100), 
                table.font.size = pct(80))
```
