---
session: "`r session <- 5; session`"
last_updated: "`r last_updated <- Sys.Date(); 
                  last_updated |> format('%Y-%m-%d')`"
class_date:
  "`r library(tidyverse);
    class_date <- read_csv('key_dates.csv', name_repair='universal') |>
    filter(Course.Element == 'Class Session',
           Item.Number == session) |>
    pull(Date); class_date |> format('%A %Y-%m-%d')`"
format: revealjs
---

{{< include _setup.qmd >}}

## Course Project Proposals

Today: Course project proposal presentations ([Official Description](../project.qmd#project-proposal-presentations))

- **6 minute presentation**
- Key topics:
  - *Animating Question*
  - *Team Roster*
- Also discuss: Possible specific questions, data sources, 
  analytical plan, anticipated challenges

. . . 

Most important: team names! 

Previous: Rat Pack, Subway Surfers, Going for Gold, *etc.*

## After Proposals

Extra Review of `R` Basics - 100% Optional

. . . 

- Variables, Vectors, Types, Control Flow

## Mini-Project #00

MP#00 due last Friday - Course Infrastructure Set-Up

::: {.incremental}

- Setup RStudio Project
- Create GitHub Account and Repo
- Connect Local Computer to GitHub
- Deploy GitHub Pages

:::

. . . 

I enjoyed getting to know (a bit more about) you!

## Mini-Project #00 

[Mini-Project #00](../mini/mini00.qmd) peer feedback assigned

- Due `r get_mp_pf_deadline(0)`
- 3 peer feedback assignments per student
  - Give 3 comments, get 3 comments
  
. . . 

[Peer Feedback Instructions](../miniprojects.qmd#peer-feedback)
can be found online

## Mini-Project #00

Interactive script automates this process: 

```{r}
#| eval: false
#| echo: true
source("https://michael-weylandt.com/STA9750/load_helpers.R")
mp_pf_perform(0, github="YOUR_GITHUB_ID")
```

Will request the secret code I gave you *via* Teams when you completed MP#00

. . . 

Will ask you a series of questions and save your 
responses in a specifically formatted file

## MP#00 Peer Feedback

Ungraded assignment, so simple feedback: 

- One strength, one weakness, one suggestion for improvement (3x)

After completion, upload `bspf` file to Brightspace (for privacy / confidentiality)

## MP PF Cycle

Aims of Mini-Project Peer Feedback:

::: {.small}

- Learn to _read_ and _evaluate_ code
- In analysis, rarely _right_ and _wrong_; 
  definitely _better_ and _worse_
- Learn tricks to improve your own site

:::

> "Good artists copy; great artists steal." -- Steve Jobs

. . . 

*Most* coding is reading - *most* reading is reading _your own old code_

## Course Support

Asynchronous Support: MS Teams

. . . 

Synchronous Support: Office Hours

- Tuesdays and Thursdays (Zoom) at 5pm

## Pre-Assignments

No pre-assignment today (no lecture) 

. . . 

Pre-Assignments resume before next class

::: {.small}

  - Day before class at 6:00pm
  - Available on course website + Brightspace after 9pm
  - Unlimited re-tries so make sure you get 30/30!
  
:::

# Proposal Presentations

{{< include _chunks/presentations.qmd >}}

# Wrap-Up

## Orientation

::: {.small}

- Team Formation  ✅
- Team Contracts  ✅
- Proposal Presentations ⬅️
- Mid-Semester Check-Ins
- Mid-Semester Peer Evaluations
- Final Presentations
- Final Reports
- Final Peer Evaluations

:::



## Next Time

::: {.small}

- Communicating Results (`quarto`)  ✅
- `R` Basics  ✅
- Data Manipulation in `R` ⬅️
  - Single-Table Data Manipulation  ✅
  - Multi-Table Data Manipulation ⬅️ 
- Data Visualization in `R`
- Getting Data into `R` 
- Statistical Modeling in `R`

:::


. . . 

**Joins and Pivots** 

- Combining multiple tidy tables into one 'analysis-ready' data set
- Rearranging data for ease of use

## Upcoming Work

Upcoming work from [course calendar](../index.qmd#calendar)

::: {.incremental}

- Weekly Pre-Assignment
- [Mini-Project #00](../mini/mini00.qmd) peer feedback
- [Mini-Project #01](../mini/mini01.qmd) due on `r get_mp_deadline(1)`

:::

. . . 

*Reminder*: Stick around for optional review

{{< include _end.qmd >}}
