---
session: "`r session <- 14; session`"
class_date:
  "`r library(tidyverse); 
    read_csv('key_dates.csv', name_repair='universal') |>
    filter(Course.Element == 'Class Session', Item.Number==session) |>
    pull(Date)`"
---

{{< include _setup.qmd >}}

## {{< var course.short >}} Mini-Projects

- Congratulations! Done with all Mini-Projects!

**Fantastic** work this semester!

## Week 13 Pre-Assignment

- Reflection on course: 
  - How far have you come?
  - What have you learned? 
  - What was helpful? What was unhelpful? 
  
Thank you for your comments!

## Grading

Returned:

- Mid-Term Check-In Feedback
- MP#03 Grades

We owe you:

- MP#04 Grades

## Final Report - Group

*Non-Technical* Presentation - Think of yourself as a "consultant" asked by a client to investigate a topic.

## Final Report - Individual

*Technical* Appendix to Group Report. Still requires writing,
context, *etc.* but this is in particular where I'm going to
look at your code. 

## Final Project Reports

Group **and** Individual Reports 

- Submitted via GitHub **and** Brightspace

Deadline extended to the day of the 'final', December 19th


**No late work accepted** (I have to submit grades!)

## Peer Assessment

On Brightspace, I have opened an additional quiz for *peer evaluation* 
of your teammates. 

- 8 questions: scale of 1 (bad) to 3 (great)

Please submit a copy for *each* of your teammates. 

- Brightspace set to allow multiple submissions.
- Due on same day as reports

. . .

If you don't submit these, **you** will receive a 0 for 
your peer evaluations

**No late work accepted** (I have to submit grades!)

## Final Project Grading

Rubric is set _high_ to give me flexibility to reward teams
that take on big challenges

Hard rubric => Grades are curved generously 

. . . 

Multiple paths to success 

If your problem is "easy" on an element (data import
in particular), that's great! Don't spend the effort 
over-complicating things. Effort is better spent elsewhere

## Instructor's Reflection



## Baruch Course Evaluations

**Short Break** to complete course evaluations

[http://baruch.cuny.edu/EVALS](http://baruch.cuny.edu/EVALS)

Roughly: 

- Scores used by central administration
- Comments used by faculty and departments to improve offerings

## Hall of Fame 

Submit [Hall of Fame Nominations](https://baruch.az1.qualtrics.com/jfe/form/SV_9Yb1mzdI4WuzjM2)

## Today

December 12 - Last Day of Class!

- Final Project *Presentations*

## Presentation Order

| Order | Team           |     | Order | Team            |
|-------|----------------|-----|-------|-----------------|
| 10    | Rat Pack       |     | 7     | Ca\$h VZ        |
| 8     | Subway Surfers |     | 6     | Listing Legends |
| 2     | Chart Toppers  |     | 9     | TDSSG           |
| 5     | Metro Mindset  |     | 3     | Broker T's      |
| 1     | Apple Watch    |     | 4     | EVengers        |


# Thanks to Charles!

# 🎊🥳🎉 \n Congratulations!!

# 

<div class="tenor-gif-embed" data-postid="5123679" data-share-method="host" data-aspect-ratio="1.47059" data-width="100%"><a href="https://tenor.com/view/its-over-ferris-bueller-go-home-done-bye-gif-5123679">Its Over GIF</a>from <a href="https://tenor.com/search/its+over-gifs">Its Over GIFs</a></div> <script type="text/javascript" async src="https://tenor.com/embed.js"></script>

