## Life Tip of the Week

### Tips for Technical Interviews

Some tips for technical interviews: 

::: {.incremental}

1. Communicate!

2. Test!

3. Anticipate the Danger Zone!

:::

## Communicate!

Talk / comment throughout a technical interview

- Live interview: vocalize thought process
- Async interview: comment all your choices

. . . 

Advantages of Communication:

::: {.incremental}

- Allow your interviewer to give "partial credit"
- Most questions aren't fully-precise, seek clarification
- Share your thought process

:::

## Test!

Check your work as you go

- Mistakes that only appear 'at scale' are rare
- Test on small data, first terms of sequence, *etc.*

Easier to check _simple output_ than code

## Test!

Suppose you are asked to compute 100th number of a sequence

- Don't code and submit
- Look at first 5 elements and check _by hand_

. . . 

Suppose you are asked to analyze a data set

- Try your code on a small data set first
- Design your data to make correct answer evident


## Danger Zone!

Know the 'sharp edges' of the tools you will be tested on: 

- `NULL` handling in `SQL`
- Missing values in `R`
- Groups of 0 or 1 observation

*etc*. 

## Technical Interviews

Your interviewer doesn't ultimately care if you get the right answer on a puzzle

. . . 

Do you have a _process_ to get the right answer on a problem that matters? 

- Do you handle edge cases? 
- Do you resolve ambiguities in problem statement? 
- Do you test well or just "code and pray"? 
