
## AI Usage Statement

At the end of your report, you **must** include a description
of the extent to which you used Generative AI tools to complete
the mini-project. This should be a one paragraph section clearly
deliniated using a collapsable Quarto 
["Callout Note"](https://quarto.org/docs/authoring/callouts.html). 
Failure to include an AI disclosure will result in an 
**automatic 25% penalty.**

*E.g.*, 

::: {.callout-note title="AI Usage Statement" collapse="true"}

No Generative AI tools were used to complete this mini-project. 

:::

or 

::: {.callout-note title="AI Usage Statement" collapse="true"}

GitHub Co-Pilot Pro was used via RStudio integration while 
completing this project. No other generative AI tools were used. 

:::

or 

::: {.callout-note title="AI Usage Statement" collapse="true"}

ChatGPT was used to help write the code in this project, but all non-code text
was generated without the use of any Generative AI tools. Additionally, ChatGPT
was used to provide additional background information on the topic and to 
brainstorm ideas for the final open-ended prompt. 

:::

Recall that Generative AI **may not** be used to write or edit any non-code
text in this course. 

These blocks should be created using the following syntax: 

````

::: {.callout-note title="AI Usage Statement" collapse="true"}

Your text goes here. 

:::

````

Make sure to use this specific type of callout (`.callout-note`), title, and
`collapse="true"` setting. 

Please contact the instructor if you have any questions about appropriate AI 
usage in this course. 

