For this mini-project, no more than **{{< meta mp_max_ec >}}** total points of 
extra credit can be be awarded. Opportunities for extra credit exist for students
who go *above and beyond* the instructor-provided scaffolding. Specific 
opportunities for extra credit can be [found below](#extra_credit).

Students pursuing careers in data analytics are strongly encouraged to go 
beyond the strict ambit of the mini-projects to 

i) further refine their skills; 
ii) learn additional techniques that can be used in the final course project; and
iii) develop a more impressive professional portfolio.

Because students are encouraged to use {{< var course.short >}} mini-projects as
the basis for a professional portfolio, the basic skeleton of each project will be
released under a fairly permissive usage license. Take advantage of it!

### Submission Instructions

After completing the analysis, write up your findings, *showing all of
your code*, using a dynamic `quarto` document and post it to your course
repository. The `qmd` file should be named `{r} I(mp_file$qmd)` (lower case!) so
the rendered document can be found at `{r} I(mp_file$html_long)` in the 
student's repository and will be served at the URL:[^sub]

> `https://YOUR_GITHUB_ID.github.io/{{< var course.repo >}}/mp{{< meta mp_num >}}.html`

You can use the helper function `mp_start` available at in the [Course Helper 
Functions](../tips.html#mp_start) to create a file with the appropriate name and some
meta-data already included. Do so by running the following command at the `R`
`Console`: 

> `source("https://michael-weylandt.com/STA9750/load_helpers.R"); mp_start(N={{< meta mp_num >}})`

After completing this mini-project, upload your rendered output and necessary
ancillary files to GitHub to make sure your site works. The `mp_submission_ready`
function in the [Course Helper Functions](../tips.html#mp_submission_ready) 
can perform some of these checks automatically. You can run this function by
running the following commands at the `R` `Console`: 

> `source("https://michael-weylandt.com/STA9750/load_helpers.R"); mp_submission_ready(N={{< meta mp_num >}})`

Once you confirm this website works (substituting `YOUR_GITHUB_ID` for the actual GitHub username provided to the professor in [MP#00](./mini00.html) of course), open 
a GitHub issue on the instructor's repository to submit your completed work. 

The easiest way to do so is by use of the `mp_submission_create` function in the
[Course Helper Functions](../tips.html#mp_submission_create), which can be used
by running the following command at the `R` `Console`: 

> `source("https://michael-weylandt.com/STA9750/load_helpers.R"); mp_submission_create(N={{< meta mp_num >}})`

Alternatively, if you wish to submit manually, open a new issue at

> `https://github.com/michaelweylandt/{{< var course.repo >}}/issues/new` .

Title the issue 
`{{< var course.short >}} YOUR_GITHUB_ID MiniProject #{{< meta mp_num >}}` 
and fill in the following text for the issue:

::: {#submission-text}

```
Hi @michaelweylandt!

I've uploaded my work for MiniProject #**{{< meta mp_num >}}** - check it out!

<https://<GITHUB_ID>.github.io/{{< var course.repo >}}/mp{{< meta mp_num >}}.html>
```

:::

At various points before and after the submission deadline, the
instructor will run some automated checks to ensure your submission
has all necessary components. Please respond to any issues raised in
a timely fashion as failing to address them may lead to a lower set
of scores when graded. 

*Additionally*, a PDF export of this report should be submitted on Brightspace. 
To create a PDF from the uploaded report, simply use your browser's 'Print to PDF'
functionality.

**NB**: The analysis outline below specifies key *tasks* you need to perform
within your write up. Your peer evaluators will check that you complete these. 
You are encouraged to do extra analysis, but the bolded **Tasks** are *mandatory*.

**NB**: Your final submission should look like a *report*, not simply a list of
facts answering questions. Add introductions, conclusions, and your own
commentary. You should be practicing both raw *coding* skills and written
*communication* in all mini-projects. There is little value in data points stated
without context or motivation.

[^sub]: Throughout this section, replace `YOUR_GITHUB_ID` with your GitHub ID 
from [Mini-Project #00](./mini00.html). Note that the automated course
infrastructure will be looking for precise formatting, so follow these 
instructions closely. 
