---
title: "{{< var course.short >}} - Week 6 Update"
author: "Michael Weylandt"
format: revealjs
execute:
  freeze: true # Done with AY-2024-FALL offering
---

## {{< var course.short >}} Mini-Project #01

👏 Thank you to everyone who took part in peer feedback! 👏

Charles and I have marked all grades - expect on Brightspace soon.

(Tech issues on our end...)

. . .

Also - let's thank Charles for going through every post manually with reminders 👏

## {{< var course.short >}} Mini-Project #01

Some popular tips:

-   The [`gt`](https://gt.rstudio.com/) makes very nice tables
-   `Quarto` allows "code folding": useful for hiding long boring code blocks

```{r echo=TRUE}
#| code-fold: true
#| code-summary: "Show the code"
1 + 1
```

You can set this globally. You also want to keep `echo: true`.

## {{< var course.short >}} Mini-Project #02

[MP#02 released](../miniprojcts/mini02.html) - Hollywood Movies

. . .

**Due October 23rd**

-   GitHub post (used for peer feedback) AND Brightspace

. . .

Pay attention to [the rubric](../miniprojects/mini02.html#rubric)

-   Writing and presentation are about 50% of your grade
-   Evaluated on *rigor* and *thoughtfulness*
-   Use what you learned from MP#01
-   Pre-processed data now available as well

## Upcoming Mini-Projects

Tentative Topics

-   MP#03: Political Analysis
-   MP#04: Retirement Forecasting

## Pre-Assignments

Brightspace - Wednesdays at 11:45

-   Reading, typically on course website
-   Brightspace auto-grades
    -   I have to manually change to completion grading

Next pre-assignment is **October 16th**

## Course Support

-   Synchronous
    -   Office Hours 4x / week
        -   MW Office Hours on **Tuesday** next week only
-   Asynchronous
    -   Piazza ($<30$ minute average response time)

## Upcoming Week

Due Wednesday at 11:45pm:

- Pre-Assignment #07 (Brightspace)
  * Introduction to plotting with `ggplot2`
- Project Proposal Peer Feedback (Vocat)

Expect back:

-   MP#01 consolidated grades
-   Project Proposal instructor feedback

## Course Project Presentations

| Team | Members                    |   | Team | Members                |
|------|----------------------------|---|------|------------------------|
| 1    | TD + VF + AG + EY + GZ     |   | 6    | JA + CPV               |
| 2    | NG + HM + TN + ZL(C)Y + YZ |   | 7    | CD + JCMB + PR + CKZF  |
| 3    | AC + EL + CL + WP          |   | 8    | HH(C)L + EO + GS + FW  |
| 4    | HA + HA + SK + VL + DS     |   | 9    | AA + LC + MAJ          |
| 5    | CC + DM + AO + HS + MT     |   | 10   | HB + SK + MK + CM + JV |

## Project Proposal Presentations

[Official Description](https://michael-weylandt.com/STA9750/project.html#project-proposal-presentations)

-   **6 minute presentation**
-   Key topics:
    -   *Animating Question*
    -   *Team Roster*
-   Also discuss: Possible specific questions, data sources, analytical plan, anticipated challenges

## Proposal Peer Feedback

Project Peer Feedback Platform: [Vocat](https://baruch.vocat.io/courses/2439)

After class: 

- I upload presentation videos
- You leave comments and scores on at least **1** presentation
  * Try to comment on "under-discussed" presentations
  * I will be looking for constructive feedback
  * Less detail than mini-prorjects
 
New tool - learning experience for all. Bear with us.

## After Proposals

Special presentation on Baruch data resources
