---
title: "{{< var course.short >}} - Week 10"
author: "Michael Weylandt"
format: revealjs
echo: true
execute:
  freeze: true # Done with AY-2024-FALL offering
---

## {{< var course.short >}} Mini-Project #03

Now [online](https://michael-weylandt.com/STA9750/miniprojects/mini03.html)

**Due November 13th**

- GitHub post (used for peer feedback) AND Brightspace
- Three Weeks: don't wait until the very end

- Should be less demanding than MP #01 and MP#02
  - Lots of little files. **No big files!**
  - Maps and election retrodiction
  
. . .

Pay attention to [the rubric](../miniprojects/mini03.html#rubric)


## {{< var course.short >}} Mini-Project #03

Tips: 

- `geom_sf` by default puts a thin grey boundary around each `geometry`. 
   Disable this by using `geom_sf(color=NA)`. 

- You can plot a state in a certain color by plotting all of its districts
  in that same color. Alternatively, use `st_combine` to combine `geometries`.
  
- Each state gets $R+2$ ECVs where $R$ is the number of congressional districts
  in that state. 
  
- `st_simplify` can "smooth out" boundaries to make things easier to plot

# Going Forward

## Upcoming Mini-Projects

Tentative Topics

- MP#04: Something financial

Any requests? 

## Pre-Assignments

Brightspace - Wednesdays at 11:45

-   Reading, typically on course website
-   Brightspace auto-grades
    -   I have to manually change to completion grading

Next pre-assignment is **November 13th**

. . .

Thank you for FAQs and (honest) team feedback. Keep it coming!

## Grading

We owe you: 

- MP#02 final average
- MP#02 peer meta-review

We *will* owe you: 

- Mid-Term Check-In Feedback

## Course Support

- Synchronous
  - Office Hours 4x / week
    - MW Office Hours on **Monday** + **Thursday**
    - CR **Tuesday** + **Friday**
    - No OH during Thanksgiving break
- Asynchronous
  - Piazza ($38$ minute average response time)
  
**Change**: MW Thursday Zoom OH now **4:00pm** to **5:00pm**

## Upcoming

Next Week: 

- Mini-Project #03
- Pre-Assignment

Nov 20: 

- MP#03 Peer Feedback
- Pre Assignment

Nov 27 - Thanksgiving Holiday (No Class on Nov 28)

- Check-In Peer Feedback (Vocat)

## Check-In Presentations

Today, we're looking for: 

- 6 minutes
- Locking in on _specific questions_
- Engagement with _existing literature_

Mainly, we want to see that you will be able to _succeed_ 

## Presentation Order

| Order| Team           |  | Order| Team            |
|------|----------------|--|------|-----------------|
| 1    | Rat Pack       |  | 6    | Ca\$h VZ        |
| 2    | Subway Surfers |  | 7    | Listing Legends |
| 3    | Chart Toppers  |  | 8    | TDSSG           |
| 4    | Metro Mindset  |  | 9    | Broker T's      |
| 5    | Apple Watch    |  | 10   | EVengers        |
